name: Create Pull Requests on changes to Development

on:
  pull_request:
    types:
      - closed

jobs:
  merged_development_pr:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' }}
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: "auto/${{github.event.pull_request.head.ref}}-into-development"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Determine Epic Branches
        id: determine-branches
        run: |
          EPIC_BRANCHES=$(git branch -r | grep -o 'origin/epic/[^ ]*' | sed 's|origin/||')
          echo $(git branch)
          echo "BRANCHES<<EOF" >> $GITHUB_ENV
          echo "$EPIC_BRANCHES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create PRs for Epic Branches
        env:
          GH_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        run: |
          IFS=$'\n'
          for branch in $BRANCHES; do
            PR_BRANCH="auto/${branch}-into-development"
            echo $branch
            echo done
            git switch -C $PR_BRANCH
            git push --set-upstream origin $PR_BRANCH
            gh pr create --base $branch --head $PR_BRANCH --title "Auto PR: ${PR_BRANCH}" --body "Update $branch branch with changes on development"
          done

#   if the PR is merged;
# create a new branch from the merged branch ref
#
