name: Create Label

on:
  workflow_call

jobs:
  create-label:
    runs-on: ubuntu-latest
    steps:
      - name: Create label if it doesn't exist
        env:
          GH_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        run: |
          LABEL_NAME="auto-pr"
          LABEL_EXISTS=$(gh label list --json name --jq ".[] | select(.name == \"$LABEL_NAME\") | .name")

          if [ -z "$LABEL_EXISTS" ]; then
            gh label create "$LABEL_NAME" --description "Label for automatically created PRs" --color "#1d76db"
            echo "Label '$LABEL_NAME' created."
          else
            echo "Label '$LABEL_NAME' already exists."
          fi
