name: SwiftFormat Lint

on:
  pull_request:
    branches: [ main ]
    
jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache SwiftFormat
      id: cache-swiftformat
      uses: actions/cache@v2
      with:
        path: |
          SwiftFormat/.build
        key: swiftformat-${{ hashFiles('**/*.swift') }}-${{ github.run_number }}
        restore-keys: |
          swiftformat-${{ hashFiles('**/*.swift') }}-
    
    - if: steps.cache-swiftformat.outputs.cache-hit != 'true'
      name: Install SwiftFormat  
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat.git
        cd SwiftFormat
        swift build -c release

    - name: Run SwiftFormat --lint
      run: |
        export PATH="$(pwd)/SwiftFormat/.build/release:$PATH"
        swiftformat --lint .
