name: SwiftFormat Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SwiftFormat
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat.git
        cd SwiftFormat
        swift build -c release

    - name: Run SwiftFormat --lint
      run: |
        export PATH="$(pwd)/SwiftFormat/.build/release:$PATH"
        swiftformat --lint .
