name: SwiftFormat Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SwiftFormat
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat.git
        cd SwiftFormat
        swift build -c release

    - name: Run SwiftFormat --lint
      run: |
        export PATH="$(pwd)/SwiftFormat/.build/release:$PATH"
        swiftformat --lint . > swiftformat-output.txt || true

    - name: Comment Lint Issues on PR
      if: steps.lint.outputs.lint-result != ''
      uses: unsplash/comment-on-pr@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        msg: |
          SwiftFormat Lint Issues:
          ```
          $(cat swiftformat-output.txt)
          ```
