name: SwiftFormat Lint

on:
  pull_request:
    branches: [ main ]
    
jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache SwiftFormat
      id: cache-swiftformat
      uses: actions/cache@v2
      with:
        path: |
          SwiftFormat
        key: swiftformat-${{ hashFiles('**/*.swift') }}-${{ github.run_number }}
        restore-keys: |
          swiftformat-${{ hashFiles('**/*.swift') }}-

    - name: Install SwiftFormat
      if: steps.cache-swiftformat.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat.git
        cd SwiftFormat
        swift build -c release

    - name: Run SwiftFormat (Lint Mode)
      id: lint
      run: |
        export PATH="$GITHUB_WORKSPACE/SwiftFormat/.build/release:$PATH"
        RESULT=$(swiftformat --lint . 2>&1) || true
        if [ -n "$RESULT" ]; then
          echo "::error::SwiftFormat lint issues found"
          echo "$RESULT"
          echo "lint-result=$RESULT" >> $GITHUB_ENV
        fi
    
    - name: Comment Lint Issues on PR
      if: env.lint-result != ''
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "${{ env.lint-result }}"
        check_for_duplicate_msg: true

