name: SwiftFormat Lint

on:
  pull_request:
    branches: [ main ]
    
jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache SwiftFormat
      id: cache-swiftformat
      uses: actions/cache@v2
      with:
        path: |
          SwiftFormat
        key: swiftformat-${{ hashFiles('**/*.swift') }}-${{ github.run_number }}
        restore-keys: |
          swiftformat-${{ hashFiles('**/*.swift') }}-

    - name: Install SwiftFormat
      if: steps.cache-swiftformat.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/nicklockwood/SwiftFormat.git
        cd SwiftFormat
        swift build -c release

    - name: Run SwiftFormat (Lint Mode)
      run: |
        swiftformat --lint . > swiftformat-output.txt || true
    
    - name: Comment Lint Issues on PR
      if: steps.lint.outputs.lint-result != ''
      uses: unsplash/comment-on-pr@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        msg: |
          SwiftFormat Lint Issues:
          ```
          $(cat swiftformat-output.txt)
          ```


